version: '3'

services:
  backend:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT}
    image: registry.jz17demo.acntech.no:5000/jz17-backend-app/${FORMATTED_BRANCH_NAME}:${BUILD_NUMBER}
